### ISSUE TITLE
Plugin not working for Android Studio Jellyfish | 2023.3.1

### ISSUE THREAD

**Issue by devonEdison** [gektor650/OkHttpProfiler-AndroidStudio-Plugin#13]
Plugin not working for Android Studio Jellyfish | 2023.3.1

**Comment by eugene-tkachenko** [comment]
Fixed in version 1.0.32
It will be available after approval from JetBrains. 
Meanwhile, you can download a new version by the link:

https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin/blob/master/OkHttpProfiler-1.0.32.zip

**Comment by devonEdison** [comment]
thank you so much! support Ukraine as well. where can I donate to support you.
