### ISSUE TITLE
Android Studio Koala not supported, need help

### ISSUE THREAD

**Issue by devonEdison** [gektor650/OkHttpProfiler-AndroidStudio-Plugin#14]
Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 11, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 7168M
Cores: 8
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.itkacher.okhttpprofiler (1.0.17)
  com.github.copilot (1.5.8.5775)

**Comment by eugene-tkachenko** [comment]
I uploaded a new version to the Plugin Marketplace. It will be available in a few days after approve.
However, you can install it manually from here:
https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin/blob/master/OkHttpProfiler-1.0.33.zip

**Comment by devonEdison** [comment]
Thank you so much. <3
