### ISSUE TITLE
Add support for Android Studio Dolphin Build 213.*

### ISSUE THREAD

**Issue by wixeless** [gektor650/OkHttpProfiler-AndroidStudio-Plugin#5]

**Comment by op123355569** [comment]
+1

**Comment by sdfgsdfgd** [comment]
YES our fav plugin stopped working with Dolphin. Pls provide support :(

**Comment by Vrungel322** [comment]
+1

**Comment by eugene-tkachenko** [comment]
Fixed in 1.0.23
Will be available in the plugins market in 2 business days.
Or you can download it directly:
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/227550
And install manually

And don't forget to support Ukraine.
We are still in the fire. 

Cheers!

**Comment by Vrungel322** [comment]
I live in Kyiv)

**Comment by eugene-tkachenko** [comment]
You meant Kyiv)
So do I. 
It doesn't cancel my request for donation for all the participants of this thread)
